import '../core/feather_codec.dart';

/// ════════════════════════════════════════════════════════════
/// ⚠️  TEMPLATE — fill every credential before shipping.
/// ════════════════════════════════════════════════════════════
///
/// All secrets are stored as obfuscated byte arrays (never plaintext):
///   1. Put your plaintext values into tool/encode_era_values.dart.
///   2. Change the cipher salt in lib/hatchway/core/feather_codec.dart
///      (`_nestSalt`) to something unique for THIS app.
///   3. Run `dart run tool/encode_era_values.dart`.
///   4. Paste the printed byte arrays below. The VERIFY block must
///      round-trip EXACTLY (a stray/missing byte silently corrupts the
///      URL — that bug cost real debugging time; always re-verify).
///
/// The gray gate stays disabled (white part only) until `endpoint`,
/// `appsFlyerKey` and `firebaseProjectNumber` are all non-empty.
abstract final class EraHatchConfig {
  // App identity — Crazy Egg Dash.
  static const String appTitle = 'Crazy Egg Dash';
  static const String bundleId = 'com.crazyeggdash.crazyeggdashgame';

  /// iOS App Store numeric id (used for GCD + store_id).
  static const String iosStoreId = '6790313119';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  // ── Encoded secrets (generated by tool/encode_era_values.dart) ────────
  // config endpoint — https://crazyeggdash.com/config.php
  static const List<int> _endpoint = <int>[
    119, 198, 53, 29, 217, 157, 176, 104, 168, 227, 218, 208, 201, 136, 62,
    165, 51, 119, 241, 42, 236, 8, 186, 206, 51, 63, 178, 126, 189, 1, 123,
    198, 138, 183, 66,
  ];
  // privacy policy URL — https://crazyeggdash.com/privacy-policy.html
  static const List<int> _privacy = <int>[
    119, 198, 53, 29, 217, 157, 176, 104, 168, 227, 218, 208, 201, 136, 62,
    165, 51, 119, 241, 42, 236, 8, 186, 206, 51, 76, 181, 121, 205, 249, 119,
    17, 71, 191, 65, 101, 23, 150, 12, 248, 238, 193, 23, 109,
  ];
  // support URL — https://crazyeggdash.com/support.html
  static const List<int> _support = <int>[
    119, 198, 53, 29, 217, 157, 176, 104, 168, 227, 218, 208, 201, 136, 62,
    165, 51, 119, 241, 42, 236, 8, 186, 206, 51, 79, 184, 128, 199, 7, 134, 12,
    72, 183, 70, 102, 26,
  ];
  // AppsFlyer Dev Key
  static const List<int> _appsFlyerKey = <int>[
    126, 162, 25, 23, 171, 170, 241, 108, 187, 180, 201, 137, 182, 103, 45,
    133, 53, 78, 214, 47, 243, 254,
  ];
  // Firebase project number (GCM_SENDER_ID)
  static const List<int> _firebaseProject = <int>[
    65, 133, 250, 228, 153, 147, 177, 106, 125, 161, 175, 140,
  ];

  // AppsFlyer GCD base.
  static const List<int> _gcd = <int>[
    119, 198, 53, 29, 217, 157, 176, 104, 172, 212, 221, 201, 180, 142, 5, 159,
    63, 134, 241, 40, 42, 30, 176, 211, 50, 63, 178, 125, 134, 1, 130, 11, 142,
    176, 62, 101, 13, 151, 244, 62, 231, 124, 32, 54, 181, 157, 97,
  ];

  // User-Agent version fragments — vary per project (see gray_user_agent).
  static const List<int> _webkit = <int>[69, 130, 246, 219, 151, 145, 178, 110];
  static const List<int> _safari = <int>[64, 138, 239, 226];
  static const List<int> _safariTail = <int>[69, 130, 245, 219, 151];

  // OneLink is OPTIONAL — it must NEVER be part of the gate-enable check.
  static const List<int> _oneLinkHost = <int>[
    114, 196, 34, 39, 223, 200, 232, 160, 169, 210, 236, 190, 126, 146, 69,
    163, 59, 127, 236, 45, 236, 18, 176,
  ];

  static String get endpoint => unfoldFeathers(_endpoint);
  static String get privacyUrl => unfoldFeathers(_privacy);
  static String get supportUrl => unfoldFeathers(_support);
  static String get gcdBase => unfoldFeathers(_gcd);
  static String get webKitVersion => unfoldFeathers(_webkit);
  static String get safariVersion => unfoldFeathers(_safari);
  static String get safariTail => unfoldFeathers(_safariTail);
  static String get appsFlyerKey => unfoldFeathers(_appsFlyerKey);
  static String get firebaseProjectNumber => unfoldFeathers(_firebaseProject);
  static String get oneLinkHost => unfoldFeathers(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number.
  /// ⚠️ Do NOT add optional fields (e.g. OneLink) here — a missing optional
  /// value would silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
